In [21]:
import numpy as np

## numpy array

In [22]:
benimListem = [20,30,40]

In [23]:
type(benimListem)

list

In [24]:
np.array(benimListem)

array([20, 30, 40])

In [25]:
type(np.array(benimListem))

numpy.ndarray

In [26]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [27]:
type(matrixListesi)

list

In [28]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [29]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros

In [32]:
## veri biliminde np.zeros() komutu, belirtilen boyutlarda tamamen sıfırlardan oluşan bir matris oluşturur.

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace

In [43]:
## linspace,genellikle veri bilimi matematiksel modelleme ve mühendislikte kullanılan, 
## belirli bir aralığı eşit parçalara bölerek sayılar üreten bir fonksiyondur.

In [44]:
## np.linspace(5:start,15:stop,5:number) number==>kaç adet sayı olacağını göster.

In [45]:
np.linspace(5,15,5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

## eye

In [46]:
## Birim matris oluşturmak için kullanılır.
## Birim matris: Ana kösegendeki tüm elemanlar bir diğer elemanlar sıfır.

## random

In [49]:
## random(): 0 ile 1 arasında ondalıklı sayılar üretir.
## randn(): Standart Normal Dağılım (ortalama=0,standart sapma=1) kurallarına göre rastgele sayılar üreten bir fonk.

In [50]:
np.random.randn(3)

array([ 0.10640596, -0.18174382,  0.94596506])

In [51]:
np.random.randn(3,3)

array([[-0.72972155, -0.28018066,  0.03442894],
       [ 0.58032557, -0.4050569 , -0.3214976 ],
       [-2.39443309,  0.54748026, -0.31283238]])

In [52]:
## randint: belirli bir aralıkta rastgele tam sayılar üretmek için kullanılan fonksiyondur.

In [57]:
np.random.randint(4,85)

54

In [59]:
np.random.randint(1,10,6)

array([4, 8, 2, 2, 7, 7], dtype=int32)

In [60]:
benimNumpyDizim = np.arange(5)

In [61]:
benimNumpyDizim

array([0, 1, 2, 3, 4])

In [63]:
benimRandomDizim = np.random.randn(4)

In [64]:
benimRandomDizim

array([-2.24263489, -1.066661  ,  0.08195101, -0.34652718])

In [67]:
benimRandomTamSayıDizim = np.random.randint(1,15,5)

In [68]:
benimRandomTamSayıDizim

array([ 8,  7,  5, 13,  7], dtype=int32)