In [2]:
import numpy as np

In [3]:
benimDizim = np.arange(15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
print(benimDizim[5])

5


In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8] = -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi = np.arange(0,24)

In [11]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
slicingDizisi = baskaDizi[4:9]

In [13]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [14]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
slicingDizisi[:] = 700

In [16]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [17]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [18]:
ornekDizi = np.arange(0,24)

In [19]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
ornekDiziKopyasi = ornekDizi.copy()

In [23]:
ornekDizi 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [25]:
ornekDiziKopyaSlicing[:] = 800

In [27]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [28]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [29]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# matrix

In [30]:
benimListem = [10,20,30],[20,30,40],[40,50,60]

In [31]:
benimMatrixDizim = np.array(benimListem)

In [33]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [34]:
benimMatrixDizim[0]

array([10, 20, 30])

In [36]:
print(benimMatrixDizim[1][2])

40


In [38]:
print(benimMatrixDizim[1,2])

40


In [40]:
print(benimMatrixDizim[1:,2])

[40 60]


In [64]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [65]:
yeniMatrix = np.array(yeniListe)

In [61]:
print(yeniMatrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [20 21 22 23 24]]


In [66]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

# operasyonlar 

In [74]:
yeniBirDizi = np.random.randint(1,100,20)

In [75]:
print(yeniBirDizi)

[69  3 30 18 79 21 43 69 43 53 12 50 90 33 37 74 49 12 16 73]


In [76]:
yeniBirDizi > 24

array([ True, False,  True, False,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
       False,  True])

In [77]:
yeniBirDizi

array([69,  3, 30, 18, 79, 21, 43, 69, 43, 53, 12, 50, 90, 33, 37, 74, 49,
       12, 16, 73], dtype=int32)

In [78]:
sonucDizisi = yeniBirDizi > 24

In [79]:
sonucDizisi

array([ True, False,  True, False,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
       False,  True])

In [80]:
yeniBirDizi

array([69,  3, 30, 18, 79, 21, 43, 69, 43, 53, 12, 50, 90, 33, 37, 74, 49,
       12, 16, 73], dtype=int32)

In [83]:
print(yeniBirDizi[sonucDizisi])

[69 30 79 43 69 43 53 50 90 33 37 74 49 73]


In [85]:
print(yeniBirDizi[yeniBirDizi > 24])

[69 30 79 43 69 43 53 50 90 33 37 74 49 73]


In [86]:
sonDizi = np.arange(0,24)

In [87]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [88]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [89]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [90]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [91]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [92]:
sonDizi / sonDizi

C:\Users\kadir\AppData\Local\Temp\ipykernel_7072\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [98]:
print(np.max(sonDizi))

23


In [97]:
print(np.min(sonDizi))

0
